spring:
    datasource:
        password: 123
        url: jdbc:mariadb://localhost/chinook
        username: student
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
